include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - unawaited_futures
    - prefer_final_locals

formatter:
  page_width: 120
  trailing_commas: preserve
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
